name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [
          10,
          12,
          14,
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Check formatting
        run: |
          npx prettier -c 'src/*.ts' 'example/**/*.{js,ts}'
      - name: Lint with eslint
        run: |
          npm run lint
      - name: Transpile ts files
        run: |
          npm run build
      - name: Run integration tests
        run: |
          ./test.sh
