name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [
          8,
          9,
          10,
          11,
          12,
          13,
          14,
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Lint with eslint
        if: ${{ matrix.node-version >= 10 }}
        run: |
          npm run lint
      - name: Run integration tests
        run: |
          ./test.sh
